version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  AfterInstall:
    - location: scripts/installScript.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startScript.sh
      timeout: 300
      runas: root
